//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace RevitWorksets {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class MyStrings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal MyStrings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("RevitWorksets.MyStrings", typeof(MyStrings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Categories.
        /// </summary>
        public static string ColumnCategories {
            get {
                return ResourceManager.GetString("ColumnCategories", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Families.
        /// </summary>
        public static string ColumnFamilies {
            get {
                return ResourceManager.GetString("ColumnFamilies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type names.
        /// </summary>
        public static string ColumnTypes {
            get {
                return ResourceManager.GetString("ColumnTypes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Arch.
        /// </summary>
        public static string DefaultWorksetArch {
            get {
                return ResourceManager.GetString("DefaultWorksetArch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Concrete.
        /// </summary>
        public static string DefaultWorksetConcrete {
            get {
                return ResourceManager.GetString("DefaultWorksetConcrete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Shared Levels and Grids.
        /// </summary>
        public static string DefaultWorksetGrids {
            get {
                return ResourceManager.GetString("DefaultWorksetGrids", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isolation.
        /// </summary>
        public static string DefaultWorksetHydro {
            get {
                return ResourceManager.GetString("DefaultWorksetHydro", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MEP.
        /// </summary>
        public static string DefaultWorksetMep {
            get {
                return ResourceManager.GetString("DefaultWorksetMep", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebars.
        /// </summary>
        public static string DefaultWorksetRebar {
            get {
                return ResourceManager.GetString("DefaultWorksetRebar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rebars_Freelength.
        /// </summary>
        public static string DefaultWorksetRebarFreelength {
            get {
                return ResourceManager.GetString("DefaultWorksetRebarFreelength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Workset name.
        /// </summary>
        public static string DisplayWorksetName {
            get {
                return ResourceManager.GetString("DisplayWorksetName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File is not workshared!.
        /// </summary>
        public static string ErrorFileIsNotWorkshared {
            get {
                return ResourceManager.GetString("ErrorFileIsNotWorkshared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set family name prefixes.
        /// </summary>
        public static string FormTitleSetFamilyPrefixes {
            get {
                return ResourceManager.GetString("FormTitleSetFamilyPrefixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Set type name prefixes.
        /// </summary>
        public static string FormTitleSetTypePrefixes {
            get {
                return ResourceManager.GetString("FormTitleSetTypePrefixes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elements processed.
        /// </summary>
        public static string MessageElementsProcessed {
            get {
                return ResourceManager.GetString("MessageElementsProcessed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Finished!.
        /// </summary>
        public static string MessageFinished {
            get {
                return ResourceManager.GetString("MessageFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No elements checked!.
        /// </summary>
        public static string MessageToCheckboxesChecked {
            get {
                return ResourceManager.GetString("MessageToCheckboxesChecked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created worksets.
        /// </summary>
        public static string MessageWorksetsCreated {
            get {
                return ResourceManager.GetString("MessageWorksetsCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Worksets.
        /// </summary>
        public static string PluginName {
            get {
                return ResourceManager.GetString("PluginName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loaded from file.
        /// </summary>
        public static string ToolStripLoadedFromFile {
            get {
                return ResourceManager.GetString("ToolStripLoadedFromFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved to file.
        /// </summary>
        public static string ToolStripSavedToFile {
            get {
                return ResourceManager.GetString("ToolStripSavedToFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings file is not found, set default settings.
        /// </summary>
        public static string ToolStripSettingsFileNotFound {
            get {
                return ResourceManager.GetString("ToolStripSettingsFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings were reset.
        /// </summary>
        public static string ToolStripSettingsReset {
            get {
                return ResourceManager.GetString("ToolStripSettingsReset", resourceCulture);
            }
        }
    }
}
